### PR TITLE
chore: deploy docs to AWS (master only)

### PR DESCRIPTION
**Pull request by anucreative**

### CODE REVIEW

**Comment by theo-mesnil** [comment]
Are you sur on master to deploy ? Because sometime we don’t have a bump with a PR. Maybe on a production branch ?

**Comment by anucreative** [comment]
> Are you sur on master to deploy ? Because sometime we don’t have a bump with a PR. Maybe on a production branch ?

Yeah, I agree. Might make it a manual step (approval) in Circle. Just testing for the moment.

**Comment by theo-mesnil** [comment]
> > Are you sur on master to deploy ? Because sometime we don’t have a bump with a PR. Maybe on a production branch ?
> 
> Yeah, I agree. Might make it a manual step (approval) in Circle. Just testing for the moment.

Yes :)

**Comment by ThomasHaddad** [comment]
Suite à une discussion avec charles, plus besoin de cette feature là

**Pull request closed without merging**
