### PR TITLE
fix Breadcrumb: remove  vertical scroll

### PR DESCRIPTION
**Pull request by RobelTekle**
Capture d’écran 2023-06-20 à 16 17 40

https://github.com/WTTJ/welcome-ui/assets/33298885/619a4e60-fd7c-4b78-8382-4d729a065496

### CODE REVIEW

**Review by mleralec — COMMENTED** [review]
maybe change the `line-height` of the Breadcrumb.Item to `normal` fix this issue ?

**Review by mleralec — APPROVED** [review]
💪🏻

**Comment by theo-mesnil** [comment]
Hey @RobelTekle did you need a release ? Or you can wait few days ?

**Comment by RobelTekle** [comment]
> Hey @RobelTekle did you need a release ? Or you can wait few days ?

Hey @theo-mesnil I can wait, it's not urgent

**Pull request merged**
